a = int(input())
b = int(input())
c = a + b
d = a - b
e = a * b
f = a / b
g = a % b
print("a + b = " + str(c))
print("a - b = " + str(d))
print("a * b = " + str(e))
print("a / b = " + str(f))
print("a % b = " + str(g))